# Generated by Django 6.0.6 on 2026-06-28 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_restaurantitem_restaurantfavorite_restaurantview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAmbientAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('ambient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='restaurants.ambient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'ambient'), name='unique_user_ambient_affinity')],
            },
        ),
        migrations.CreateModel(
            name='UserCuisineAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='restaurants.cuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'cuisine'), name='unique_user_cuisine_affinity')],
            },
        ),
        migrations.CreateModel(
            name='UserPriceAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='restaurants.pricerange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'price_range'), name='unique_user_price_affinity')],
            },
        ),
    ]
