# Generated by Django 6.0.6 on 2026-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantitem_restaurantfavorite_restaurantview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='embedding_stale',
            field=models.BooleanField(default=True),
        ),
    ]
