# Generated by Django 6.0.6 on 2026-06-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_embedding_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual (site)'), ('google', 'Google Places')], default='manual', max_length=20),
        ),
    ]
