# Generated by Django 6.0.6 on 2026-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_external_id_restaurant_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
