# Generated by Django 6.0.6 on 2026-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_restaurant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
