# Generated by Django 6.0.6 on 2026-06-28 04:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_restaurant_embedding_stale'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RestaurantEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('document', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='restaurants.restaurant')),
            ],
        ),
    ]
