# Generated by Django 6.0.6 on 2026-06-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_info',
            field=models.BooleanField(default=False),
        ),
    ]
