# Generated by Django 6.0.6 on 2026-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allow_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
